name: Build BBC Console linux 64 bit clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLANG_VER: 15

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{env.CLANG_VER}} main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install nasm clang-${{env.CLANG_VER}} clang-tools-${{env.CLANG_VER}} clang-tidy-${{env.CLANG_VER}} 
        
    - name: make
      run: |
        cd console/linux
        sed '/^.*CXX .*$/d' makefile >makefile.clang
        export CXX="clang-${{env.CLANG_VER}} -Wall -Wextra -Wpedantic -Wno-pointer-arith -Wno-sign-compare -Wno-unused-parameter -Wno-gnu-case-range -Wno-gnu-binary-literal -std=c11 -Wstrict-prototypes -Wold-style-definition -I ../../include -I ../../../BBCSDL/include -Dasm=__asm -Dintptr_t=__intptr_t -fprofile-instr-generate -fcoverage-mapping -g "
        export CC="clang-${{env.CLANG_VER}} -Wall -Wextra -Wpedantic -Wno-pointer-arith -Wno-sign-compare -Wno-unused-parameter -Wno-gnu-case-range -Wno-gnu-binary-literal -std=c11 -Wstrict-prototypes -Wold-style-definition -I ../../include -I ../../../BBCSDL/include -Dasm=__asm -Dintptr_t=__intptr_t -fprofile-instr-generate -fcoverage-mapping -g "
        make --file=makefile.clang

    - name: 'Tar files'
      run: |
        ls -la
        tar -czf bbcbasic-console.tgz bbcbasic lib examples licence.txt tests

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: bbcbasic-console
        path: bbcbasic-console.tgz    
      
    - name: 'Run Tests'
      run: |
        if [ -f default.profraw ]; then
          rm default.profraw
        fi

        if [ -f tests/bbcbasic-*.profraw ]; then
          rm tests/bbcbasic-*.profraw
        fi

        if [ -f bbcbasic.profdata ]; then
          rm bbcbasic.profdata
        fi

        echo Running tests
        export LLVM_PROFILE_FILE="bbcbasic-%m.profraw" 

        echo QUIT | ./bbcbasic tests/ALLTESTS.bbc

        echo Running llvm-profdata-${{env.CLANG_VER}}
        llvm-profdata-${{env.CLANG_VER}} merge -sparse -instr tests/bbcbasic-*.profraw -o bbcbasic.profdata

        echo Running llvm-cov-${{env.CLANG_VER}}
        llvm-cov-${{env.CLANG_VER}} show -show-regions -format=html -output-dir=coverage -instr-profile=bbcbasic.profdata ./bbcbasic
        llvm-cov-${{env.CLANG_VER}} report ./bbcbasic -instr-profile=bbcbasic.profdata

        tar -czf bbcbasic-console-coverage.tgz coverage/
        
